config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "kittens#index"
  resources :kittens

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.json { render json: @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      flash[:success] = "Your kitten has been created!"
      redirect_to @kitten
    else
      flash.now[:error] = "The kitten couldn't be created."
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      flash[:success] = "Your kitten hsa been updated!"
      redirect_to @kitten
    else
      flash[:error] = "The kitten couldn't be updated."
      render :edit
    end

  end

  def destroy
    @kitten = Kitten.find(params[:id])
    if @kitten.destroy
      flash[:notice] = "Your kitten has been deleted!"
      redirect_to root_path
    end
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_flash_message.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :cuteness %>
    <%= form.text_field :cuteness %>
  </div>

  <div>
    <%= form.label :softness %>
    <%= form.text_field :softness %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit kitten</h1>

<%= render "form", kitten: @kitten %>

<%= link_to "Delete kitten", @kitten, method: :delete %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>

<%= render "flash_message" %>

<ul>
  <% @kittens.each do |k| %>
    <li>
      <p>Name: <%= k.name %></p>
      <p>Age: <%= k.age %></p>
      <p>Cuteness: <%= k.cuteness %></p>
      <p>Softness: <%= k.softness %></p>
    </li>
  <% end %>
</ul>

<%= link_to "New kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>New kitten</h1>

<%= render "form", kitten: @kitten %>

app/views/kittens/show.html.erb
<h1>Kitten <%= @kitten.id %></h1>

<%= render "flash_message" %>

<div>
  <p>Name: <%= @kitten.name %></p>
  <p>Age: <%= @kitten.age %></p>
  <p>Cuteness: <%= @kitten.cuteness %></p>
  <p>Softness: <%= @kitten.softness %></p>

  <%= link_to "Edit kitten", edit_kitten_path(@kitten) %>
  <%= button_to "Delete kitten", @kitten, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>